### ISSUE TITLE
Ruby issue in speechRecognizer on Lion?

### ISSUE THREAD

**Issue by anlek** [floere/james#11]
/Users/andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /Users/andrew/.rvm/gems/ruby-1.9.2-p290/gems/james-0.7.1/lib/james/inputs/audio.rb:31: syntax error, unexpected tLABEL (SyntaxError)
      def speechRecognizer sender, didRecognizeCommand: command
                                                       ^
/Users/andrew/.rvm/gems/ruby-1.9.2-p290/gems/james-0.7.1/lib/james/inputs/audio.rb:47: syntax error, unexpected keyword_end, expecting $end
    from /Users/andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/andrew/.rvm/gems/ruby-1.9.2-p290/gems/james-0.7.1/lib/james.rb:19:in `<top (required)>'
    from /Users/andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/andrew/.rvm/gems/ruby-1.9.2-p290/gems/james-0.7.1/aux/james/cli.rb:1:in`<top (required)>'
    from /Users/andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/andrew/.rvm/gems/ruby-1.9.2-p290/gems/james-0.7.1/bin/james:22:in `rescue in <top (required)>'
    from /Users/andrew/.rvm/gems/ruby-1.9.2-p290/gems/james-0.7.1/bin/james:16:in`<top (required)>'
    from /Users/andrew/.rvm/gems/ruby-1.9.2-p290/bin/james:19:in `load'
    from /Users/andrew/.rvm/gems/ruby-1.9.2-p290/bin/james:19:in`<main>'

Here is my RVM info:
ruby-1.9.2-p290:

  system:
    uname:       "Darwin Andrews-MacBook-Pro.local 11.0.0 Darwin Kernel Version 11.0.0: Sat Jun 18 12:56:35 PDT 2011; root:xnu-1699.22.73~1/RELEASE_X86_64 x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin11)"
    zsh:         "/bin/zsh => zsh 4.3.11 (i386-apple-darwin11.0)"

  rvm:
    version:      "rvm 1.6.31 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]"

  ruby:
    interpreter:  "ruby"
    version:      "1.9.2p290"
    date:         "2011-07-09"
    platform:     "x86_64-darwin11.0.0"
    patchlevel:   "2011-07-09 revision 32553"
    full_version: "ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.0.0]"

  homes:
    gem:          "/Users/andrew/.rvm/gems/ruby-1.9.2-p290"
    ruby:         "/Users/andrew/.rvm/rubies/ruby-1.9.2-p290"

  binaries:
    ruby:         "/Users/andrew/.rvm/rubies/ruby-1.9.2-p290/bin/ruby"
    irb:          "/Users/andrew/.rvm/rubies/ruby-1.9.2-p290/bin/irb"
    gem:          "/Users/andrew/.rvm/rubies/ruby-1.9.2-p290/bin/gem"
    rake:         "/Users/andrew/.rvm/gems/ruby-1.9.2-p290/bin/rake"

  environment:
    PATH:         "/Users/andrew/.rvm/gems/ruby-1.9.2-p290/bin:/Users/andrew/.rvm/gems/ruby-1.9.2-p290@global/bin:/Users/andrew/.rvm/rubies/ruby-1.9.2-p290/bin:/Users/andrew/.rvm/bin:/Users/andrew/bin:/Users/andrew/.bin:/usr/local/homebrew/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin"
    GEM_HOME:     "/Users/andrew/.rvm/gems/ruby-1.9.2-p290"
    GEM_PATH:     "/Users/andrew/.rvm/gems/ruby-1.9.2-p290:/Users/andrew/.rvm/gems/ruby-1.9.2-p290@global"
    MY_RUBY_HOME: "/Users/andrew/.rvm/rubies/ruby-1.9.2-p290"
    IRBRC:        "/Users/andrew/.rvm/rubies/ruby-1.9.2-p290/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by floere** [comment]
Hi Andrew,

Thanks for all the debug output. It appears you're using Ruby 1.9.2.
James needs MacRuby. Please refer to the Installation header in the README here: https://github.com/floere/james

Cheers and thanks,
   Florian
